project_id = "lpyhtbvycxqjjqpwjxyh"

[functions.flowith-proxy]
verify_jwt = false

[functions.auth]
verify_jwt = false

[functions.ai-proofread]
verify_jwt = false

[functions.generate-asset]
verify_jwt = false

[functions.memorization-content]
verify_jwt = false

[functions.pica-notion]
verify_jwt = false

[functions.proofreading-assignments]
verify_jwt = false

[functions.proofreading-practices]
verify_jwt = false

[functions.spelling-practices]
verify_jwt = false

[functions.public-access]
enabled = true
verify_jwt = false
import_map = "./functions/public-access/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/public-access/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/public-access/*.html" ]
